#!/bin/sh

for i in $( efibootmgr | grep -oE '^Boot[0-9]+' | grep -oE '[0-9]+' )
    do efibootmgr -b $i -B -q
done
efibootmgr -O -q

UKI_PRIMARY=$( ls -t1 /boot/efi/EFI/Linux/ | head -n1 )
UKI_SECONDARY=$( ls -t1 /boot/efi/EFI/Linux/ | head -n2 | tail -n1 )

mkdir -p /boot/efi/EFI/BOOT
cp "/boot/efi/EFI/Linux/${UKI_PRIMARY}" /boot/efi/EFI/BOOT/BOOTX64.efi

efibootmgr --create --disk /dev/sda1 --label 'Debian Primary EFI Stub UKI' --loader "/EFI/Linux/${UKI_PRIMARY}" -q
efibootmgr --create --disk /dev/sda1 --label 'Debian Secondary EFI Stub UKI' --loader "/EFI/Linux/${UKI_SECONDARY}" -q
efibootmgr -o 0000,0001
