#!/bin/sh

version="$1"
[ -x /usr/bin/dracut ] || exit 1
[ -z "${version}" ] && exit 0

echo "dracut: generating /boot/efi/EFI/Linux/linux-${version}.efi"
dracut \
  --uefi \
  --add "crypt dm systemd-cryptsetup tpm2-tss" \
  --force \
  --kernel-cmdline "root=UUID=###target_root_uuid### rd.luks.uuid=###target_luks_uuid### rd.luks.name=###target_luks_uuid###=luks_root rd.luks.options=###target_luks_uuid###=tpm2-device=auto,tpm2-measure-pcr=yes rd.shell=0" \
  --verbose \
  "/boot/efi/EFI/Linux/linux-${version}.efi" --kver "${version}"
