#!/bin/sh

if ! command -v systemd-cryptenroll > /dev/null; then
    printf 'errore: installare comando systemd-cryptenroll\n' >&2
    exit 1
fi

ROOT="$( blkid | grep 'PARTLABEL="ROOT"' | grep -oE '^[^ :]+' )"
TPM='/dev/tpmrm0'
systemd-cryptenroll --wipe-slot=tpm2 --tpm2-device=$TPM --tpm2-pcrs=7+15:sha256=0000000000000000000000000000000000000000000000000000000000000000 $ROOT
