# richiede di aver pre-registrato la password admin e un token jwt sul cluster con il comando:
# kubectl create secret generic minecraft-secret --from-literal=login-pin="<PIN NUMERICO>"
#
### per copiare i dati del mondo in caso ci sia un savefile esistente, applicare questo yaml, poi:
### scalare il deployment esistente a 0:
# kubectl scale deployment minecraft-deployment --replicas=0
### creare un pod temporaneo per il trasferimento dati:
# kubectl apply -f - <<EOF
# apiVersion: v1
# kind: Pod
# metadata:
#   name: data-loader
# spec:
#   volumes:
#     - name: data-loader-volume
#       persistentVolumeClaim:
#         claimName: minecraft-data-pvc
#   containers:
#     - name: data-loader
#       image: alpine:latest
#       command: ["sleep", "infinity"]
#       volumeMounts:
#         - name: data-loader-volume
#           mountPath: /data
# EOF
### copiare i dati nel pod temporaneo:
# kubectl cp defcon data-loader:/data/defcon
### entrare a bordo del container temporaneo se necessario per aggiustare i dati:
# kubectl exec -it data-loader -- /bin/sh
### cancellare il pod temporaneo e riportare il deployment a una replica:
# kubectl delete pod/data-loader
# kubectl scale deployment minecraft-deployment --replicas=1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-default
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
      annotations:
        dns.custom/name: "minecraft"
        dns.custom/zone: "atmtc.eu"
    spec:
      hostNetwork: true
      volumes:
        - name: minecraft-data-volume
          persistentVolumeClaim:
            claimName: minecraft-data-pvc
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 60
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 60
      containers:
        - name: minecraft
          image: registry.fedoraproject.org/fedora-minimal:latest
          ports:
            - containerPort: 15857
          volumeMounts:
            - name: minecraft-data-volume
              mountPath: /data
          workingDir: /data
          resources:
            requests:
              cpu: "2000m"
              memory: "2Gi"
            limits:
              cpu: "2000m"
              memory: "4Gi"
          stdin: true
          tty: true
          env:
            - name: SERVER_PIN
              valueFrom:
                secretKeyRef:
                  name: minecraft-secret
                  key: login-pin
          command: ["/bin/sh", "-c"]
          args:
            - |
              microdnf install -y --nodocs curl jq java-25-openjdk-headless
              microdnf clean all

              ### setup regole server e whitelist

              echo 'eula=true' > eula.txt

              cat <<'EOF' > whitelist.json
              [
                {"uuid": "8b3798c1-a6ca-3efe-add7-948f821f5c96", "name": "brg"},
                {"uuid": "ccae4ace-fe97-482a-aac5-0b3a43cd1a17", "name": "springymochi"},
                {"uuid": "4588e5ed-563d-3a76-a94b-61a600b8b116", "name": "tap3o"},
                {"uuid": "b1b8d219-4958-3dab-9770-0267ecdcf72d", "name": "marcochiodo"},
                {"uuid": "41cef4ff-d4fe-3ac6-a8e9-4df3695aaade", "name": "bu$a"},
                {"uuid": "e42e552b-b129-3d9f-96b9-148709e61443", "name": "ClaraMilani"},
                {"uuid": "40fe2335-d5c4-387a-a022-5e6327b213c3", "name": "_IC3"},
                {"uuid": "7d49c588-9003-3d23-96bf-52d82636e1d6", "name": "Frozeskin"}
              ]
              EOF

              cat <<'EOF' > server.properties
              motd=§c§lDEFCON SERVER §e§lV4 INAFFONDABILE§r | §b§oReplicato su K8s

              white-list=true
              enforce-whitelist=true

              enable-code-of-conduct=false
              enable-jmx-monitoring=false
              enable-query=false
              enable-rcon=false
              enable-status=true
              management-server-enabled=false
              function-permission-level=4

              allow-flight=true
              difficulty=hard
              gamemode=survival
              force-gamemode=true

              level-name=defcon
              level-seed=
              level-type=minecraft\:normal
              view-distance=16
              simulation-distance=12
              spawn-protection=1

              max-players=8
              online-mode=false
              hide-online-players=true
              pause-when-empty-seconds=60
              region-file-compression=lz4
              server-port=15857
              EOF

              ### micro datapack per autenticazione via pin

              DP="/data/defcon/datapacks/auth"
              mkdir -p "$DP/data/a/function" "$DP/data/a/functions"
              mkdir -p "$DP/data/minecraft/tags/function" "$DP/data/minecraft/tags/functions"

              echo '{"pack":{"pack_format":81,"description":"Auth System"}}' > "$DP/pack.mcmeta"

              echo '{"values":["a:tick"]}' > "$DP/data/minecraft/tags/function/tick.json"
              cp "$DP/data/minecraft/tags/function/tick.json" "$DP/data/minecraft/tags/functions/tick.json"

              cat <<EOF > "$DP/data/a/function/tick.mcfunction"
              scoreboard objectives add pin trigger
              scoreboard objectives add l custom:leave_game
              scoreboard objectives add tries dummy
              scoreboard objectives add timer dummy

              execute as @a[scores={l=1..}] run tag @s remove ok
              execute as @a[scores={l=1..}] run scoreboard players reset @s tries
              execute as @a[scores={l=1..}] run scoreboard players reset @s timer
              scoreboard players reset @a[scores={l=1..}] l

              execute as @a[tag=!ok] run scoreboard players enable @s pin
              effect give @a[tag=!ok] blindness 2 0 true
              effect give @a[tag=!ok] slowness 2 255 true
              effect give @a[tag=!ok] mining_fatigue 2 255 true
              title @a[tag=!ok] actionbar {"text":"Enter PIN: /trigger pin set <PIN>","color":"yellow"}

              execute as @a[tag=!ok,scores={pin=${SERVER_PIN}}] run effect clear @s
              execute as @a[tag=!ok,scores={pin=${SERVER_PIN}}] run scoreboard players reset @s tries
              execute as @a[tag=!ok,scores={pin=${SERVER_PIN}}] run scoreboard players reset @s timer
              execute as @a[tag=!ok,scores={pin=${SERVER_PIN}}] run tag @s add ok

              execute as @a[tag=!ok,scores={pin=1..}] unless score @s pin matches ${SERVER_PIN} run scoreboard players add @s tries 1
              execute as @a[tag=!ok,scores={pin=1..}] unless score @s pin matches ${SERVER_PIN} run tellraw @s {"text":"Incorrect PIN!","color":"red"}
              execute as @a[scores={pin=1..}] run scoreboard players reset @s pin

              execute as @a[tag=!ok,scores={tries=3..}] run kick @s "Too many incorrect PIN attempts!"
              EOF
              cp "$DP/data/a/function/tick.mcfunction" "$DP/data/a/functions/tick.mcfunction"

              ### download e lancio server.jar

              META_URL=$(curl -s https://piston-meta.mojang.com/mc/game/version_manifest_v2.json | jq -r '.latest.release as $r | .versions[] | select(.id == $r) | .url')
              curl -o server.jar $(curl -s "$META_URL" | jq -r '.downloads.server.url')

              exec java -Xms2G -Xmx2G -XX:+UseTransparentHugePages -jar server.jar nogui
