# per registrare nuovi utenti:
# kubectl exec -it deployment/prosody-deployment -- prosodyctl register <username> prosody.atmtc.eu <password>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prosody-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-default
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prosody-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prosody
  template:
    metadata:
      labels:
        app: prosody
      annotations:
        dns.custom/name: "prosody"
        dns.custom/zone: "atmtc.eu"
    spec:
      hostNetwork: true
      volumes:
        - name: prosody-data-volume
          persistentVolumeClaim:
            claimName: prosody-data-pvc
        - name: prosody-certs-volume
          hostPath:
            path: /etc/ssl/private
            type: Directory
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 60
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 60
      containers:
        - name: prosody
          image: alpine:latest
          ports:
            - name: c2s
              containerPort: 5222
            - name: http-upload
              containerPort: 5281
          volumeMounts:
            - name: prosody-data-volume
              mountPath: /data
            - name: prosody-certs-volume
              mountPath: /etc/ssl/private
              readOnly: true
          workingDir: /data
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "384Mi"
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add --no-cache prosody || exit 1

              mkdir -p /data/prosody_store
              mkdir -p /tmp/certs

              cp /etc/ssl/private/atmtc.eu.pem /tmp/certs/atmtc.eu.pem
              cp /etc/ssl/private/atmtc.eu.key /tmp/certs/atmtc.eu.key
              chown -R prosody:prosody /data /tmp/certs
              chmod 400 /tmp/certs/atmtc.eu.key

              cat <<'EOF' > /etc/prosody/prosody.cfg.lua
              admins = { "admin@prosody.atmtc.eu" }

              data_path = "/data/prosody_store"
              daemonize = false
              log = { "*console" }

              modules_enabled = {
                "roster";       -- Gestione della rubrica contatti e delle richieste di autorizzazione presenza
                "saslauth";     -- Negoziazione autenticazione sicura utenti (SCRAM-SHA-1/256, PLAIN)
                "tls";          -- Crittografia del canale di trasporto (STARTTLS su porta 5222)
                "disco";        -- Service Discovery (XEP-0030): scoperta delle feature attive sul server
                "posix";        -- Gestione segnali di sistema (reload configurazione e gestione processo)
                "private";      -- Private XML Storage (XEP-0049): memorizzazione cloud impostazioni client
                "vcard4";       -- Schede profilo vCard4/XML (XEP-0292): gestione avatar e dettagli utente
                "vcard_legacy"; -- Schede profilo vCard-temp (XEP-0054): fallback avatar per client legacy
                "version";      -- Risponde alle richieste di versione software (XEP-0092)
                "uptime";       -- Fornisce il tempo di attività del server (XEP-0012)
                "time";         -- Sincronizzazione dell'orario con il server (XEP-0202)
                "ping";         -- Verifica periodica dello stato di attività della connessione (XEP-0199)
                "pep";          -- Personal Eventing Protocol (XEP-0163): necessario per OMEMO (bundle chiavi)
                "admin_adhoc";  -- Comandi amministrativi via chat (XEP-0050) per utenti admin
                "carbons";      -- Message Carbons (XEP-0280): sincronizzazione cronologia su più dispositivi
                "mam";          -- Message Archive Management (XEP-0313): storico messaggi salvato sul server
                "smacks";       -- Stream Management (XEP-0198): previene disconnessioni al cambio rete (Wi-Fi/4G)
                "blocking";     -- Blocking Command (XEP-0191): blocco utenti indesiderati
                "csi_simple";   -- Client State Indication (XEP-0352): ottimizza batteria e traffico in background
              }

              modules_disabled = { "s2s" }
              s2s_ports = {}

              c2s_require_encryption = true
              c2s_ports = { 5222 }
              https_ports = { 5281 }
              http_ports = {}

              VirtualHost "prosody.atmtc.eu"
                ssl = {
                  key = "/tmp/certs/atmtc.eu.key";
                  certificate = "/tmp/certs/atmtc.eu.pem";
                }
                allow_registration = false

              Component "upload.prosody.atmtc.eu" "http_file_share"
                http_host = "prosody.atmtc.eu"
                http_external_url = "https://prosody.atmtc.eu:5281/"
                http_file_share_size_limit = 50 * 1024 * 1024     -- 50 MB
                http_file_share_expires_after = 60 * 60 * 24 * 30 -- 30 days

              Component "conference.prosody.atmtc.eu" "muc"
                restrict_room_creation = "local"
                modules_enabled = {
                  "muc_mam";
                }
              EOF

              chown -R prosody:prosody /etc/prosody

              exec su -s /bin/sh prosody -c "prosody"
