apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
      annotations:
        dns.custom/name: "www"
        dns.custom/zone: "atmtc.eu"
    spec:
      hostNetwork: true
      volumes:
        - name: website-certs-volume
          hostPath:
            path: /etc/ssl/private
            type: Directory
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 30
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 30
      containers:
        - name: website
          image: alpine:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: website-certs-volume
              mountPath: /etc/ssl/private
              readOnly: true
          resources:
            limits:
              memory: "200Mi"
              cpu: "1000m"
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add --no-cache git caddy

              cat <<'EOF' > Caddyfile
              www.atmtc.eu {
                tls /etc/ssl/private/atmtc.eu.pem /etc/ssl/private/atmtc.eu.key
                handle {
                  root * website
                  file_server
                }
              }
              EOF

              git clone https://github.com/atmtck/website.git
              (while true; do
                sleep 3600
                git -C website pull
              done) &

              caddy fmt --overwrite Caddyfile
              caddy run
